version: "3.8"

services:
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: aeris_ml_service
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    container_name: aeris_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - ml-service
    restart: always