"use client";

import { Progress } from "@/components/ui/progress";
import { useAQIStore } from "@/store/useAQIStore";

export default function ForecastChart() {
  const dashboard = useAQIStore((state) => state.dashboard);
  const forecast = dashboard?.forecast;

  if (!forecast) {
    return (
      <div className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-none">
        <h3 className="font-serif text-xl font-semibold text-[#111827]">Forecast Overview</h3>
        <p className="mt-1 text-sm text-[#6B7280]">Waiting for prediction...</p>
      </div>
    );
  }

  const confidence = Math.round(forecast.confidence * 100);

  return (
    <div className="rounded-2xl border border-[#E5E7EB] bg-white p-6 shadow-none space-y-8">
      <div>
        <h3 className="font-serif text-xl font-semibold text-[#111827]">AI Forecast Overview</h3>
        <p className="mt-1 text-sm text-[#6B7280]">Latest prediction generated by the forecasting model.</p>
      </div>

      <div className="text-center py-4">
        <p className="text-xs font-medium uppercase tracking-[0.14em] text-[#6B7280]">Predicted AQI</p>
        <h2 className="mt-2 font-serif text-[48px] font-bold tracking-tight text-[#111827] leading-none">
          {forecast.predicted_aqi.toFixed(1)}
        </h2>
        <span className="mt-4 inline-block rounded-full bg-[#DCFCE7] px-4 py-1 text-xs font-semibold text-[#15803D]">
          {forecast.category}
        </span>
      </div>

      <div className="space-y-2 max-w-md mx-auto">
        <div className="flex items-center justify-between text-xs font-medium text-[#6B7280]">
          <span>Model Confidence</span>
          <span>{confidence}%</span>
        </div>
        <Progress value={confidence} className="h-2.5 w-full bg-[#FAFBFC]" />
      </div>
    </div>
  );
}