"use client";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import { Progress } from "@/components/ui/progress";

import { useAQIStore } from "@/store/useAQIStore";

export default function ForecastChart() {
  const dashboard = useAQIStore(
    (state) => state.dashboard
  );

  const forecast = dashboard?.forecast;

  if (!forecast) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Forecast Overview</CardTitle>
          <CardDescription>
            Waiting for prediction...
          </CardDescription>
        </CardHeader>
      </Card>
    );
  }

  const confidence =
    Math.round(forecast.confidence * 100);

  return (
    <Card>

      <CardHeader>

        <CardTitle>

          AI Forecast Overview

        </CardTitle>

        <CardDescription>

          Latest prediction generated by the forecasting model

        </CardDescription>

      </CardHeader>

      <CardContent className="space-y-8">

        <div className="text-center">

          <p className="text-sm text-muted-foreground">
            Predicted AQI
          </p>

          <h2 className="mt-2 text-5xl font-bold tracking-tight">
            {forecast.predicted_aqi.toFixed(1)}
          </h2>

          <p className="mt-3 text-base font-medium text-muted-foreground">
            {forecast.category}
          </p>

        </div>

        <div className="space-y-2">

          <div className="flex items-center justify-between text-sm">

            <span>Model Confidence</span>

            <span>{confidence}%</span>

          </div>

          <Progress value={confidence} />

        </div>

      </CardContent>

    </Card>
  );
}